#!/bin/sh -x

LSB=`lsb_release -sc`

if [ "$LSB" != "wheezy" ] ; then
        if [ -f "/etc/systemd/system/webiopi.service" ] ; then 
       		systemctl enable webiopi         
		systemctl start webiopi
	else
		cp /usr/share/webiopi/webiopi.service /etc/systemd/system
                systemctl enable webiopi
                systemctl start webiopi
        fi
else 
	if [ -f "/etc/init.d/webiopi" ] ; then
		update-rc.d webiopi defaults
		/etc/init.d/webiopi start
	fi
fi
 
