#!/bin/sh -x

LSB=`lsb_release -sc`

if [ "$LSB" != "wheezy" ] ; then
        if [ -f "/etc/systemd/system/webiopi.service" ] ; then 
		systemctl disable webiopi 
        fi
else
	if [ -f "/etc/init.d/webiopi" ] ; then
		update-rc.d webiopi remove  
	fi
fi
 
