Yet Another WebIOPi+: com.trouch.webiopi.client.PiHttpClient Class Reference
com.trouch.webiopi.client.PiHttpClient Class Reference
Public Member Functions
PiHttpClient (String host)
PiHttpClient (String host, int port)
String sendRequest (String method, String path) throws Exception
Public Member Functions inherited from com.trouch.webiopi.client.PiClient
PiClient (String protocol, String host, int port)
void setCredentials (String login, String password)
abstract String sendRequest (String method, String path) throws Exception
Static Public Attributes
static final int DEFAULT_PORT = 8000
Additional Inherited Members
Static Public Member Functions inherited from com.trouch.webiopi.client.PiClient
static String encodeCredentials (String login, String password)
Protected Attributes inherited from com.trouch.webiopi.client.PiClient
String urlBase
String auth
Detailed Description
Definition at line 23 of file PiHttpClient.java.
Constructor & Destructor Documentation
com.trouch.webiopi.client.PiHttpClient.PiHttpClient (String host)
Definition at line 26 of file PiHttpClient.java.
com.trouch.webiopi.client.PiHttpClient.PiHttpClient (String host, int port)
Definition at line 30 of file PiHttpClient.java.
Member Function Documentation
String com.trouch.webiopi.client.PiHttpClient.sendRequest (String method, String path) throws Exception
Definition at line 35 of file PiHttpClient.java.
References com.trouch.webiopi.client.PiClient.auth, setup.url, and com.trouch.webiopi.client.PiClient.urlBase.
Referenced by webiopi.clients.Macro.call(), webiopi.clients.GPIO.digitalRead(), webiopi.clients.GPIO.digitalWrite(), webiopi.clients.Temperature.getCelsius(), webiopi.clients.Distance.getCentimeter(), webiopi.clients.Temperature.getFahrenheit(), webiopi.clients.GPIO.getFunction(), webiopi.clients.Pressure.getHectoPascal(), webiopi.clients.Distance.getInch(), webiopi.clients.Temperature.getKelvin(), webiopi.clients.Luminosity.getLux(), webiopi.clients.Distance.getMillimeter(), webiopi.clients.Pressure.getPascal(), webiopi.clients.GPIO.portRead(), webiopi.clients.GPIO.portWrite(), webiopi.clients.ADC.read(), webiopi.clients.PWM.readAngle(), webiopi.clients.ADC.readFloat(), webiopi.clients.ADC.readVolt(), com.trouch.webiopi.client.PiMixedClient.sendRequest(), webiopi.clients.GPIO.setFunction(), webiopi.clients.DAC.write(), webiopi.clients.PWM.writeAngle(), webiopi.clients.DAC.writeFloat(), and webiopi.clients.DAC.writeVolt().
Member Data Documentation
final int com.trouch.webiopi.client.PiHttpClient.DEFAULT_PORT = 8000 static
Definition at line 24 of file PiHttpClient.java.
Referenced by Test.main().
The documentation for this class was generated from the following file:
java/client/src/com/trouch/webiopi/client/PiHttpClient.java