Yet Another WebIOPi+: webiopi.devices.sensor.Luminosity Class Reference
webiopi.devices.sensor.Luminosity Class Reference
Public Member Functions
def __family__
def __getLux__
def getLux
Detailed Description
Definition at line 123 of file __init__.py.
Member Function Documentation
def webiopi.devices.sensor.Luminosity.__family__ (self)
Definition at line 124 of file __init__.py.
def webiopi.devices.sensor.Luminosity.__getLux__ (self)
Definition at line 127 of file __init__.py.
References webiopi.decorators.rest.request(), and coap-client.response.
Referenced by webiopi.devices.sensor.Luminosity.getLux().
def webiopi.devices.sensor.Luminosity.getLux (self)
Definition at line 132 of file __init__.py.
References webiopi.devices.sensor.Luminosity.__getLux__().
The documentation for this class was generated from the following file:
python/webiopi/devices/sensor/__init__.py