Yet Another WebIOPi+: webiopi.devices.sensor.Humidity Class Reference
webiopi.devices.sensor.Humidity Class Reference
Public Member Functions
def __family__
def __getHumidity__
def getHumidity
def getHumidityPercent
Detailed Description
Definition at line 172 of file __init__.py.
Member Function Documentation
def webiopi.devices.sensor.Humidity.__family__ (self)
Definition at line 173 of file __init__.py.
def webiopi.devices.sensor.Humidity.__getHumidity__ (self)
Definition at line 176 of file __init__.py.
References webiopi.decorators.rest.request(), and coap-client.response.
Referenced by webiopi.devices.sensor.Humidity.getHumidity(), and webiopi.devices.sensor.Humidity.getHumidityPercent().
def webiopi.devices.sensor.Humidity.getHumidity (self)
Definition at line 181 of file __init__.py.
References webiopi.devices.sensor.Humidity.__getHumidity__(), webiopi.decorators.rest.request(), and coap-client.response.
def webiopi.devices.sensor.Humidity.getHumidityPercent (self)
Definition at line 186 of file __init__.py.
References webiopi.devices.sensor.Humidity.__getHumidity__().
The documentation for this class was generated from the following file:
python/webiopi/devices/sensor/__init__.py