Yet Another WebIOPi+: com.trouch.webiopi.client.devices.Device Class Reference
com.trouch.webiopi.client.devices.Device Class Reference
Public Member Functions
Device (PiClient client, String deviceName, String type)
String sendRequest (String method, String subPath)
Protected Attributes
String path
Private Attributes
PiClient client
Detailed Description
Definition at line 19 of file Device.java.
Constructor & Destructor Documentation
com.trouch.webiopi.client.devices.Device.Device (PiClient client, String deviceName, String type)
Definition at line 24 of file Device.java.
References com.trouch.webiopi.client.devices.Device.client.
Member Function Documentation
String com.trouch.webiopi.client.devices.Device.sendRequest (String method, String subPath)
Definition at line 34 of file Device.java.
References com.trouch.webiopi.client.PiClient.sendRequest().
Referenced by webiopi.clients.Macro.call(), com.trouch.webiopi.client.devices.digital.GPIO.digitalRead(), webiopi.clients.GPIO.digitalRead(), com.trouch.webiopi.client.devices.digital.GPIO.digitalWrite(), webiopi.clients.GPIO.digitalWrite(), com.trouch.webiopi.client.devices.sensor.Temperature.getCelsius(), webiopi.clients.Temperature.getCelsius(), webiopi.clients.Distance.getCentimeter(), com.trouch.webiopi.client.devices.sensor.Temperature.getFahrenheit(), webiopi.clients.Temperature.getFahrenheit(), com.trouch.webiopi.client.devices.digital.GPIO.getFunction(), webiopi.clients.GPIO.getFunction(), com.trouch.webiopi.client.devices.sensor.Pressure.getHectoPascal(), webiopi.clients.Pressure.getHectoPascal(), webiopi.clients.Distance.getInch(), webiopi.clients.Temperature.getKelvin(), com.trouch.webiopi.client.devices.sensor.Luminosity.getLux(), webiopi.clients.Luminosity.getLux(), com.trouch.webiopi.client.devices.sensor.Distance.getMillimeter(), webiopi.clients.Distance.getMillimeter(), com.trouch.webiopi.client.devices.sensor.Pressure.getPascal(), webiopi.clients.Pressure.getPascal(), webiopi.clients.GPIO.portRead(), webiopi.clients.GPIO.portWrite(), webiopi.clients.ADC.read(), com.trouch.webiopi.client.devices.analog.PWM.readAngle(), webiopi.clients.PWM.readAngle(), com.trouch.webiopi.client.devices.analog.ADC.readFloat(), webiopi.clients.ADC.readFloat(), webiopi.clients.ADC.readVolt(), com.trouch.webiopi.client.devices.digital.GPIO.setFunction(), webiopi.clients.GPIO.setFunction(), webiopi.clients.DAC.write(), com.trouch.webiopi.client.devices.analog.PWM.writeAngle(), webiopi.clients.PWM.writeAngle(), com.trouch.webiopi.client.devices.analog.DAC.writeFloat(), webiopi.clients.DAC.writeFloat(), com.trouch.webiopi.client.devices.analog.DAC.writeVolt(), and webiopi.clients.DAC.writeVolt().
Member Data Documentation
PiClient com.trouch.webiopi.client.devices.Device.client private
Definition at line 21 of file Device.java.
Referenced by com.trouch.webiopi.client.devices.Device.Device().
String com.trouch.webiopi.client.devices.Device.path protected
Definition at line 22 of file Device.java.
Referenced by webiopi.protocols.http.HTTPHandler.logRequest(), com.trouch.webiopi.client.devices.digital.NativeGPIO.NativeGPIO(), and webiopi.clients.RESTAPI.sendRequest().
The documentation for this class was generated from the following file:
java/client/src/com/trouch/webiopi/client/devices/Device.java