Yet Another WebIOPi+: com.trouch.webiopi.client.PiCoapClient Class Reference
com.trouch.webiopi.client.PiCoapClient Class Reference
Public Member Functions
PiCoapClient (String host)
PiCoapClient (String host, int port)
String sendRequest (String method, String path) throws Exception
Public Member Functions inherited from com.trouch.webiopi.client.PiClient
PiClient (String protocol, String host, int port)
void setCredentials (String login, String password)
abstract String sendRequest (String method, String path) throws Exception
Static Public Attributes
static final int DEFAULT_PORT = 5683
Private Attributes
CoapClient client
Additional Inherited Members
Static Public Member Functions inherited from com.trouch.webiopi.client.PiClient
static String encodeCredentials (String login, String password)
Protected Attributes inherited from com.trouch.webiopi.client.PiClient
String urlBase
String auth
Detailed Description
Definition at line 24 of file PiCoapClient.java.
Constructor & Destructor Documentation
com.trouch.webiopi.client.PiCoapClient.PiCoapClient (String host)
Definition at line 28 of file PiCoapClient.java.
com.trouch.webiopi.client.PiCoapClient.PiCoapClient (String host, int port)
Definition at line 33 of file PiCoapClient.java.
Member Function Documentation
String com.trouch.webiopi.client.PiCoapClient.sendRequest (String method, String path) throws Exception
Definition at line 39 of file PiCoapClient.java.
References webiopi.decorators.rest.request(), coap-client.response, and com.trouch.webiopi.client.PiClient.urlBase.
Referenced by webiopi.clients.Macro.call(), webiopi.clients.GPIO.digitalRead(), webiopi.clients.GPIO.digitalWrite(), webiopi.clients.Temperature.getCelsius(), webiopi.clients.Distance.getCentimeter(), webiopi.clients.Temperature.getFahrenheit(), webiopi.clients.GPIO.getFunction(), webiopi.clients.Pressure.getHectoPascal(), webiopi.clients.Distance.getInch(), webiopi.clients.Temperature.getKelvin(), webiopi.clients.Luminosity.getLux(), webiopi.clients.Distance.getMillimeter(), webiopi.clients.Pressure.getPascal(), webiopi.clients.GPIO.portRead(), webiopi.clients.GPIO.portWrite(), webiopi.clients.ADC.read(), webiopi.clients.PWM.readAngle(), webiopi.clients.ADC.readFloat(), webiopi.clients.ADC.readVolt(), com.trouch.webiopi.client.PiMixedClient.sendRequest(), webiopi.clients.GPIO.setFunction(), webiopi.clients.DAC.write(), webiopi.clients.PWM.writeAngle(), webiopi.clients.DAC.writeFloat(), and webiopi.clients.DAC.writeVolt().
Member Data Documentation
CoapClient com.trouch.webiopi.client.PiCoapClient.client private
Definition at line 26 of file PiCoapClient.java.
final int com.trouch.webiopi.client.PiCoapClient.DEFAULT_PORT = 5683 static
Definition at line 25 of file PiCoapClient.java.
Referenced by com.trouch.webiopi.client.PiMulticastClient.PiMulticastClient().
The documentation for this class was generated from the following file:
java/client/src/com/trouch/webiopi/client/PiCoapClient.java