Yet Another WebIOPi+: com.trouch.webiopi.client.PiClient Class Reference
com.trouch.webiopi.client.PiClient Class Reference abstract
Public Member Functions
PiClient (String protocol, String host, int port)
void setCredentials (String login, String password)
abstract String sendRequest (String method, String path) throws Exception
Static Public Member Functions
static String encodeCredentials (String login, String password)
Protected Attributes
String urlBase
String auth
Detailed Description
Definition at line 19 of file PiClient.java.
Constructor & Destructor Documentation
com.trouch.webiopi.client.PiClient.PiClient (String protocol, String host, int port)
Definition at line 28 of file PiClient.java.
Member Function Documentation
static String com.trouch.webiopi.client.PiClient.encodeCredentials (String login, String password) static
Definition at line 24 of file PiClient.java.
References org.apache.commons.codec.binary.Base64.encodeBase64String().
Referenced by com.trouch.webiopi.client.PiClient.setCredentials().
abstract String com.trouch.webiopi.client.PiClient.sendRequest (String method, String path) throws Exception abstract
Referenced by webiopi.clients.Macro.call(), webiopi.clients.GPIO.digitalRead(), webiopi.clients.GPIO.digitalWrite(), webiopi.clients.Temperature.getCelsius(), webiopi.clients.Distance.getCentimeter(), webiopi.clients.Temperature.getFahrenheit(), webiopi.clients.GPIO.getFunction(), webiopi.clients.Pressure.getHectoPascal(), webiopi.clients.Distance.getInch(), webiopi.clients.Temperature.getKelvin(), webiopi.clients.Luminosity.getLux(), webiopi.clients.Distance.getMillimeter(), webiopi.clients.Pressure.getPascal(), webiopi.clients.GPIO.portRead(), webiopi.clients.GPIO.portWrite(), webiopi.clients.ADC.read(), webiopi.clients.PWM.readAngle(), webiopi.clients.ADC.readFloat(), webiopi.clients.ADC.readVolt(), com.trouch.webiopi.client.devices.Device.sendRequest(), webiopi.clients.GPIO.setFunction(), webiopi.clients.DAC.write(), webiopi.clients.PWM.writeAngle(), webiopi.clients.DAC.writeFloat(), and webiopi.clients.DAC.writeVolt().
void com.trouch.webiopi.client.PiClient.setCredentials (String login, String password)
Definition at line 32 of file PiClient.java.
References com.trouch.webiopi.client.PiClient.encodeCredentials().
Referenced by Test.main(), and com.trouch.webiopi.client.PiMixedClient.setCredentials().
Member Data Documentation
String com.trouch.webiopi.client.PiClient.auth protected
Definition at line 22 of file PiClient.java.
Referenced by com.trouch.webiopi.client.PiHttpClient.sendRequest(), webiopi.clients.PiMixedClient.sendRequest(), and webiopi.clients.PiMixedClient.setCredentials().
String com.trouch.webiopi.client.PiClient.urlBase protected
Definition at line 21 of file PiClient.java.
Referenced by com.trouch.webiopi.client.PiHttpClient.sendRequest(), and com.trouch.webiopi.client.PiCoapClient.sendRequest().
The documentation for this class was generated from the following file:
java/client/src/com/trouch/webiopi/client/PiClient.java