Yet Another WebIOPi+: python/native/cpuinfo.h File Reference
cpuinfo.h File Reference
Functions
int get_rpi_revision (void)
Function Documentation
int get_rpi_revision (void)
Definition at line 53 of file cpuinfo.c.
References get_cpuinfo_revision().
Referenced by initGPIO(), and setup().