Yet Another WebIOPi+: script Namespace Reference
script Namespace Reference
Functions
def setup
def destroy
def loop
def HelloWorld
def PrintTime
def getLightHours
def setLightHours
def getMode
def setMode
def getSensor
Variables
GPIO = webiopi.GPIO
int SWITCH = 21
int SERVO = 23
int LED0 = 24
int LED1 = 25
int LIGHT = 17
int HOUR_ON = 8
int HOUR_OFF = 18
int HEATER = 7
int MIN = 22
int MAX = 24
AUTO = True
tuple serial = Serial("ttyACM0", 9600)
list sensors = [0 for a in range(6)]
Function Documentation
def script.destroy ()
Definition at line 28 of file script.py.
Referenced by loop(), and webiopi.utils.loader.unloadScripts().
def script.getLightHours ()
Definition at line 48 of file script.py.
Referenced by setLightHours().
def script.getMode ()
Definition at line 40 of file script.py.
Referenced by setMode().
def script.getSensor (channel)
Definition at line 35 of file script.py.
def script.HelloWorld (first, last)
Definition at line 52 of file script.py.
def script.loop ()
Definition at line 28 of file script.py.
References destroy().
def script.PrintTime ()
Definition at line 58 of file script.py.
def script.setLightHours (on, off)
Definition at line 55 of file script.py.
References getLightHours().
def script.setMode (mode)
Definition at line 47 of file script.py.
References getMode().
def script.setup (void)
Definition at line 15 of file script.py.
Referenced by webiopi.utils.loader.loadScript().
Variable Documentation
script.AUTO = True
Definition at line 6 of file script.py.
script.GPIO = webiopi.GPIO
Definition at line 8 of file script.py.
int script.HEATER = 7
Definition at line 3 of file script.py.
int script.HOUR_OFF = 18
Definition at line 9 of file script.py.
int script.HOUR_ON = 8
Definition at line 8 of file script.py.
int script.LED0 = 24
Definition at line 11 of file script.py.
int script.LED1 = 25
Definition at line 12 of file script.py.
int script.LIGHT = 17
Definition at line 6 of file script.py.
int script.MAX = 24
Definition at line 5 of file script.py.
int script.MIN = 22
Definition at line 4 of file script.py.
list script.sensors = [0 for a in range(6)]
Definition at line 8 of file script.py.
tuple script.serial = Serial("ttyACM0", 9600)
Definition at line 7 of file script.py.
int script.SERVO = 23
Definition at line 10 of file script.py.
int script.SWITCH = 21
Definition at line 9 of file script.py.