Yet Another WebIOPi+: webiopi.devices.analog.advrspidc Namespace Reference
webiopi.devices.analog.advrspidc Namespace Reference
Classes
class AD5161DC
class AD5204DC
class AD5263DC
class AD5290DC
class AD8403DC
class ADVRSPIDC
class ADVRSPIDCMULTI
class ADVRSPIDCSINGLE
Functions
def __init__
def __str__
def __analogRead__
def __init__
def __analogWrite__
def __init__
Variables
int ADDRESS_BITS = 3
name
values
chips
slice
Function Documentation
def webiopi.devices.analog.advrspidc.__analogRead__ (self, channel, diff = False)
Definition at line 74 of file advrspidc.py.
def webiopi.devices.analog.advrspidc.__analogWrite__ (self, channel, value)
Definition at line 89 of file advrspidc.py.
References webiopi.utils.logger.debug(), and webiopi.utils.logger.printBytes().
def webiopi.devices.analog.advrspidc.__init__ (self, chip, vref, channelCount, resolution, name)
Definition at line 61 of file advrspidc.py.
References webiopi.utils.types.toint().
Referenced by webiopi.devices.analog.advrspidc.__init__().
def webiopi.devices.analog.advrspidc.__init__ (self, chip, vref, channelCount, resolution, name, chipsCount)
Definition at line 82 of file advrspidc.py.
References webiopi.devices.analog.advrspidc.__init__().
def webiopi.devices.analog.advrspidc.__init__ (self, chip = 0, vref = 5.0, chips = 1)
Definition at line 141 of file advrspidc.py.
References webiopi.devices.analog.advrspidc.__init__(), and webiopi.utils.types.toint().
def webiopi.devices.analog.advrspidc.__str__ (self)
Definition at line 69 of file advrspidc.py.
Variable Documentation
int webiopi.devices.analog.advrspidc.ADDRESS_BITS = 3
Definition at line 137 of file advrspidc.py.
webiopi.devices.analog.advrspidc.chips
Definition at line 84 of file advrspidc.py.
webiopi.devices.analog.advrspidc.name
Definition at line 64 of file advrspidc.py.
webiopi.devices.analog.advrspidc.slice
Definition at line 85 of file advrspidc.py.
webiopi.devices.analog.advrspidc.values
Definition at line 65 of file advrspidc.py.