Yet Another WebIOPi+: webiopi.devices.memory.at24 Namespace Reference
webiopi.devices.memory.at24 Namespace Reference
Classes
class EE24BASIC
class EE24X1024_2
class EE24X128
class EE24X256
class EE24X32
class EE24X512
class EE24X64
class EE24XXXX
Functions
def __init__
def __str__
def __readMemoryByte__
def __writeMemoryByte__
def __readMemoryWord__
def __writeMemoryWord__
def __readMemoryLong__
def __writeMemoryLong__
def readMemoryBytes
def writeMemoryBytes
def splitAddress
def writeMemoryBytesPaged
def read16Byte
def read16Bytes
def write16Byte
def write16Bytes
def __init__
def __init__
Variables
int I2CMAXBUFF = 1024
_pageSize
_writeTime
name
Function Documentation
def webiopi.devices.memory.at24.__init__ (self, slave, byteCount, pageSize, writeTime, name)
Definition at line 64 of file at24.py.
References webiopi.utils.types.toint().
Referenced by webiopi.devices.memory.at24.__init__().
def webiopi.devices.memory.at24.__init__ (self, slave = 0x50, writeTime = 25)
Definition at line 207 of file at24.py.
References webiopi.devices.memory.at24.__init__().
def webiopi.devices.memory.at24.__init__ (self, slave = 0x50, writeTime = 5, slots = 4096)
Definition at line 215 of file at24.py.
References webiopi.devices.memory.at24.__init__(), and webiopi.utils.types.toint().
def webiopi.devices.memory.at24.__readMemoryByte__ (self, address)
Definition at line 83 of file at24.py.
def webiopi.devices.memory.at24.__readMemoryLong__ (self, address)
Definition at line 103 of file at24.py.
def webiopi.devices.memory.at24.__readMemoryWord__ (self, address)
Definition at line 92 of file at24.py.
def webiopi.devices.memory.at24.__str__ (self)
Definition at line 77 of file at24.py.
def webiopi.devices.memory.at24.__writeMemoryByte__ (self, address, value)
Definition at line 87 of file at24.py.
def webiopi.devices.memory.at24.__writeMemoryLong__ (self, address, value)
Definition at line 108 of file at24.py.
def webiopi.devices.memory.at24.__writeMemoryWord__ (self, address, value)
Definition at line 97 of file at24.py.
def webiopi.devices.memory.at24.read16Byte (self, addrHigh, addrLow)
Definition at line 169 of file at24.py.
def webiopi.devices.memory.at24.read16Bytes (self, addrHigh, addrLow, count)
Definition at line 173 of file at24.py.
def webiopi.devices.memory.at24.readMemoryBytes (self, start = 0, stop = None)
Definition at line 120 of file at24.py.
def webiopi.devices.memory.at24.splitAddress (self, address)
Definition at line 142 of file at24.py.
def webiopi.devices.memory.at24.write16Byte (self, addrHigh, addrLow, byte)
Definition at line 187 of file at24.py.
def webiopi.devices.memory.at24.write16Bytes (self, addrHigh, addrLow, buff)
Definition at line 190 of file at24.py.
def webiopi.devices.memory.at24.writeMemoryBytes (self, start = 0, byteValues = [])
Definition at line 133 of file at24.py.
def webiopi.devices.memory.at24.writeMemoryBytesPaged (self, start, byteValues)
Definition at line 145 of file at24.py.
Variable Documentation
webiopi.devices.memory.at24._pageSize
Definition at line 71 of file at24.py.
webiopi.devices.memory.at24._writeTime
Definition at line 72 of file at24.py.
int webiopi.devices.memory.at24.I2CMAXBUFF = 1024
Definition at line 58 of file at24.py.
webiopi.devices.memory.at24.name
Definition at line 73 of file at24.py.