Yet Another WebIOPi+: webiopi.devices.clock.mcprtc Namespace Reference
webiopi.devices.clock.mcprtc Namespace Reference
Classes
class MCP7940
Functions
def __init__
def __str__
def __family__
def __getSec__
def __setSec__
def __getMin__
def __setMin__
def __getHrs__
def __setHrs__
def __getDay__
def __setDay__
def __getMon__
def __setMon__
def __getYrs__
def __setYrs__
def __getDow__
def __setDow__
def __getDateTime__
def __getDate__
def __getTime__
def __readMemoryByte__
def __writeMemoryByte__
def __readMemoryWord__
def __writeMemoryWord__
def __readMemoryLong__
def __writeMemoryLong__
def start
def stop
def __getCon__
def __setCon__
Variables
int SEC = 0x00
int MIN = 0x01
int HRS = 0x02
int DOW = 0x03
int DAY = 0x04
int MON = 0x05
int YRS = 0x06
int CON = 0x07
int RAM = 0x20
int SEC_MASK = 0
int MIN_MASK = 0
int HRS_MASK = 0
int DOW_MASK = 0
int DAY_MASK = 0
int MON_MASK = 0
int YRS_MASK = 0
int CON_MASK = 0
int CON_DEFAULT = 0
int ST = 0
Function Documentation
def webiopi.devices.clock.mcprtc.__family__ (self)
Definition at line 98 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getCon__ (self)
Definition at line 244 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getDate__ (self)
Definition at line 182 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getDateTime__ (self)
Definition at line 172 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getDay__ (self)
Definition at line 131 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getDow__ (self)
Definition at line 155 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getHrs__ (self)
Definition at line 121 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getMin__ (self)
Definition at line 114 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getMon__ (self)
Definition at line 138 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getSec__ (self)
Definition at line 104 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getTime__ (self)
Definition at line 189 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__getYrs__ (self)
Definition at line 148 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__init__ (self, control = None)
Definition at line 77 of file mcprtc.py.
References webiopi.utils.types.toint().
def webiopi.devices.clock.mcprtc.__readMemoryByte__ (self, address)
Definition at line 199 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__readMemoryLong__ (self, address)
Definition at line 215 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__readMemoryWord__ (self, address)
Definition at line 205 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setCon__ (self, value)
Definition at line 248 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setDay__ (self, value)
Definition at line 135 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setDow__ (self, value)
Definition at line 159 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setHrs__ (self, value)
Definition at line 125 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setMin__ (self, value)
Definition at line 118 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setMon__ (self, value)
Definition at line 142 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setSec__ (self, value)
Definition at line 108 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__setYrs__ (self, value)
Definition at line 152 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__str__ (self)
Definition at line 95 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__writeMemoryByte__ (self, address, value)
Definition at line 202 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.__writeMemoryLong__ (self, address, value)
Definition at line 219 of file mcprtc.py.
References webiopi.decorators.rest.request().
def webiopi.devices.clock.mcprtc.__writeMemoryWord__ (self, address, value)
Definition at line 209 of file mcprtc.py.
def webiopi.devices.clock.mcprtc.start (self)
Definition at line 231 of file mcprtc.py.
References webiopi.decorators.rest.request().
def webiopi.devices.clock.mcprtc.stop (self)
Definition at line 237 of file mcprtc.py.
Variable Documentation
int webiopi.devices.clock.mcprtc.CON = 0x07
Definition at line 58 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.CON_DEFAULT = 0
Definition at line 71 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.CON_MASK = 0
Definition at line 70 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.DAY = 0x04
Definition at line 55 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.DAY_MASK = 0
Definition at line 66 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.DOW = 0x03
Definition at line 54 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.DOW_MASK = 0
Definition at line 65 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.HRS = 0x02
Definition at line 53 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.HRS_MASK = 0
Definition at line 64 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.MIN = 0x01
Definition at line 52 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.MIN_MASK = 0
Definition at line 63 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.MON = 0x05
Definition at line 56 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.MON_MASK = 0
Definition at line 67 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.RAM = 0x20
Definition at line 59 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.SEC = 0x00
Definition at line 51 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.SEC_MASK = 0
Definition at line 62 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.ST = 0
Definition at line 73 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.YRS = 0x06
Definition at line 57 of file mcprtc.py.
int webiopi.devices.clock.mcprtc.YRS_MASK = 0
Definition at line 68 of file mcprtc.py.