Yet Another WebIOPi+: webiopi.devices.bus Namespace Reference
webiopi.devices.bus Namespace Reference
Classes
class Bus
Functions
def loadModule
def unloadModule
def loadModules
def unloadModules
def __modulesLoaded__
def modulesLoaded
def checkAllBus
Variables
dictionary BUSLIST
Function Documentation
def webiopi.devices.bus.__modulesLoaded__ (modules, lines)
Definition at line 52 of file bus.py.
Referenced by webiopi.devices.bus.modulesLoaded().
def webiopi.devices.bus.checkAllBus ()
Definition at line 73 of file bus.py.
References webiopi.devices.bus.modulesLoaded().
def webiopi.devices.bus.loadModule (module)
Definition at line 28 of file bus.py.
References webiopi.utils.logger.debug().
Referenced by webiopi.devices.onewire.loadExtraModule(), and webiopi.devices.bus.loadModules().
def webiopi.devices.bus.loadModules (bus)
Definition at line 35 of file bus.py.
References webiopi.utils.version.info, webiopi.devices.bus.loadModule(), and webiopi.devices.bus.modulesLoaded().
Referenced by webiopi.devices.bus.Bus.__init__().
def webiopi.devices.bus.modulesLoaded (bus)
Definition at line 60 of file bus.py.
References webiopi.devices.bus.__modulesLoaded__().
Referenced by webiopi.devices.bus.checkAllBus(), and webiopi.devices.bus.loadModules().
def webiopi.devices.bus.unloadModule (module)
Definition at line 32 of file bus.py.
Referenced by webiopi.devices.bus.unloadModules().
def webiopi.devices.bus.unloadModules (bus)
Definition at line 46 of file bus.py.
References webiopi.utils.version.info, and webiopi.devices.bus.unloadModule().
Variable Documentation
dictionary webiopi.devices.bus.BUSLIST
Initial value:
 = {
     "I2C": {"enabled": False, "gpio": {0:"SDA", 1:"SCL", 2:"SDA", 3:"SCL"}, "modules": ["i2c-bcm2708", "i2c-dev"]},
     "SPI": {"enabled": False, "gpio": {7:"CE1", 8:"CE0", 9:"MISO", 10:"MOSI", 11:"SCLK"}, "modules": ["spi-bcm2708", "spidev"]},
     "UART": {"enabled": False, "gpio": {14:"TX", 15:"RX"}},
     "ONEWIRE": {"enabled": False, "gpio": {4:"DATA"}, "modules": ["w1-gpio"], "wait": 2}
 }
Definition at line 21 of file bus.py.