Yet Another WebIOPi+: webiopi-client Namespace Reference
webiopi-client Namespace Reference
Variables
tuple client = PiHttpClient("192.168.1.234")
tuple gpio = NativeGPIO(client)
state = True
tuple dac = DAC(client, "dac1")
tuple adc = ADC(client, "adc1")
float value = 0.0
tuple temp = Temperature(client, "temp0")
tuple val = adc.readFloat(1)
tuple t = temp.getCelsius()
Variable Documentation
tuple webiopi-client.adc = ADC(client, "adc1")
Definition at line 21 of file webiopi-client.py.
Referenced by Test.main().
tuple webiopi-client.client = PiHttpClient("192.168.1.234")
Definition at line 5 of file webiopi-client.py.
tuple webiopi-client.dac = DAC(client, "dac1")
Definition at line 18 of file webiopi-client.py.
Referenced by Test.main().
tuple webiopi-client.gpio = NativeGPIO(client)
Definition at line 13 of file webiopi-client.py.
Referenced by disablePWM(), enablePWM(), getPulse(), isPWMEnabled(), Test.main(), pulseAngle(), pulseRatio(), pwmLoop(), and resetPWM().
webiopi-client.state = True
Definition at line 15 of file webiopi-client.py.
tuple webiopi-client.t = temp.getCelsius()
Definition at line 43 of file webiopi-client.py.
tuple webiopi-client.temp = Temperature(client, "temp0")
Definition at line 25 of file webiopi-client.py.
tuple webiopi-client.val = adc.readFloat(1)
Definition at line 39 of file webiopi-client.py.
float webiopi-client.value = 0.0
Definition at line 22 of file webiopi-client.py.
Referenced by get_function(), input(), Test.main(), outputSequence(), and py_output().