Yet Another WebIOPi+: webiopi.utils.logger Namespace Reference
webiopi.utils.logger Namespace Reference
Functions
def setInfo
def setDebug
def debugEnabled
def logToFile
def debug
def info
def warn
def error
def exception
def printBytes
Variables
tuple LOG_FORMATTER = logging.Formatter(fmt='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
tuple ROOT_LOGGER = logging.getLogger()
tuple CONSOLE_HANDLER = logging.StreamHandler()
tuple LOGGER = logging.getLogger("WebIOPi")
Function Documentation
def webiopi.utils.logger.debug (message)
Definition at line 27 of file logger.py.
Referenced by webiopi.devices.analog.advrspidc.__analogWrite__(), webiopi.devices.digital.gpio.NativeGPIO.close(), webiopi.devices.bus.loadModule(), and webiopi.devices.digital.gpio.NativeGPIO.setup().
def webiopi.utils.logger.debugEnabled ()
Definition at line 19 of file logger.py.
def webiopi.utils.logger.error (message)
Definition at line 36 of file logger.py.
def webiopi.utils.logger.exception (message)
Definition at line 39 of file logger.py.
Referenced by webiopi.__main__.main(), webiopi.protocols.coap.COAPServer.processMessage(), webiopi.protocols.http.HTTPServer.run(), and webiopi.protocols.coap.COAPServer.run().
def webiopi.utils.logger.info (message)
Definition at line 30 of file logger.py.
def webiopi.utils.logger.logToFile (filename)
Definition at line 22 of file logger.py.
Referenced by webiopi.__main__.main().
def webiopi.utils.logger.printBytes (buff)
Definition at line 42 of file logger.py.
Referenced by webiopi.devices.analog.advrspidc.__analogWrite__().
def webiopi.utils.logger.setDebug ()
Definition at line 16 of file logger.py.
Referenced by webiopi.__main__.main().
def webiopi.utils.logger.setInfo ()
Definition at line 13 of file logger.py.
def webiopi.utils.logger.warn (message)
Definition at line 33 of file logger.py.
Variable Documentation
tuple webiopi.utils.logger.CONSOLE_HANDLER = logging.StreamHandler()
Definition at line 7 of file logger.py.
tuple webiopi.utils.logger.LOG_FORMATTER = logging.Formatter(fmt='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
Definition at line 3 of file logger.py.
tuple webiopi.utils.logger.LOGGER = logging.getLogger("WebIOPi")
Definition at line 11 of file logger.py.
tuple webiopi.utils.logger.ROOT_LOGGER = logging.getLogger()
Definition at line 4 of file logger.py.