Yet Another WebIOPi+: webiopi.devices.manager Namespace Reference
webiopi.devices.manager Namespace Reference
Functions
def findDeviceClass
def addDevice
def addDeviceInstance
def closeDevices
def getDevicesJSON
Variables
list PACKAGES = [serial, digital, analog, sensor, shield, clock, memory]
Function Documentation
def webiopi.devices.manager.addDevice (name, device, args)
Definition at line 21 of file manager.py.
References webiopi.devices.manager.addDeviceInstance(), and webiopi.devices.manager.findDeviceClass().
def webiopi.devices.manager.addDeviceInstance (name, dev, args)
Definition at line 31 of file manager.py.
Referenced by webiopi.devices.manager.addDevice().
def webiopi.devices.manager.closeDevices ()
Definition at line 48 of file manager.py.
def webiopi.devices.manager.findDeviceClass (name)
Definition at line 9 of file manager.py.
Referenced by webiopi.devices.manager.addDevice().
def webiopi.devices.manager.getDevicesJSON (compact = False)
Definition at line 56 of file manager.py.
Variable Documentation
list webiopi.devices.manager.PACKAGES = [serial, digital, analog, sensor, shield, clock, memory]
Definition at line 8 of file manager.py.