Yet Another WebIOPi+: cambot Namespace Reference
cambot Namespace Reference
Functions
def set_speed
def left_stop
def left_forward
def left_backward
def right_stop
def right_forward
def right_backward
def go_forward
def go_backward
def turn_left
def turn_right
def stop
def setup
def destroy
Variables
GPIO = webiopi.GPIO
int L1 = 17
int L2 = 18
int LS = 21
int R1 = 23
int R2 = 24
int RS = 25
Function Documentation
def cambot.destroy ()
Definition at line 108 of file cambot.py.
def cambot.go_backward ()
Definition at line 73 of file cambot.py.
References left_backward(), and right_backward().
def cambot.go_forward ()
Definition at line 68 of file cambot.py.
References left_forward(), and right_forward().
def cambot.left_backward ()
Definition at line 45 of file cambot.py.
Referenced by go_backward(), and turn_left().
def cambot.left_forward ()
Definition at line 41 of file cambot.py.
Referenced by go_forward(), and turn_right().
def cambot.left_stop ()
Definition at line 37 of file cambot.py.
Referenced by stop().
def cambot.right_backward ()
Definition at line 60 of file cambot.py.
Referenced by go_backward(), and turn_right().
def cambot.right_forward ()
Definition at line 56 of file cambot.py.
Referenced by go_forward(), and turn_left().
def cambot.right_stop ()
Definition at line 52 of file cambot.py.
Referenced by stop().
def cambot.set_speed (speed)
Definition at line 29 of file cambot.py.
Referenced by setup().
def cambot.setup (void)
Definition at line 93 of file cambot.py.
Referenced by module_setup(), and setup().
def cambot.stop ()
Definition at line 88 of file cambot.py.
References left_stop(), and right_stop().
Referenced by webiopi.__main__.main(), and setup().
def cambot.turn_left ()
Definition at line 78 of file cambot.py.
References left_backward(), and right_forward().
def cambot.turn_right ()
Definition at line 83 of file cambot.py.
References left_forward(), and right_backward().
Variable Documentation
cambot.GPIO = webiopi.GPIO
Definition at line 8 of file cambot.py.
Referenced by Test.main().
int cambot.L1 = 17
Definition at line 15 of file cambot.py.
int cambot.L2 = 18
Definition at line 16 of file cambot.py.
int cambot.LS = 21
Definition at line 17 of file cambot.py.
int cambot.R1 = 23
Definition at line 20 of file cambot.py.
int cambot.R2 = 24
Definition at line 21 of file cambot.py.
int cambot.RS = 25
Definition at line 22 of file cambot.py.