Yet Another WebIOPi+: webiopi.devices.analog.advrspi Namespace Reference
webiopi.devices.analog.advrspi Namespace Reference
Classes
class AD5160
class AD5161S
class AD5162
class AD5165
class AD5200
class AD5201
class AD5204
class AD5206
class AD5263S
class AD5290
class AD8400
class AD8402
class AD8403
class ADVRSPI
class ADVRSPIMULTI
class ADVRSPISINGLE
Functions
def __str__
def __init__
def __analogRead__
def __analogWrite__
def __init__
def __init__
Variables
int CHANNEL_MASK = 0
name
values
value
Function Documentation
def webiopi.devices.analog.advrspi.__analogRead__ (self, channel, diff = False)
Definition at line 68 of file advrspi.py.
def webiopi.devices.analog.advrspi.__analogWrite__ (self, channel, value)
Definition at line 73 of file advrspi.py.
def webiopi.devices.analog.advrspi.__init__ (self, chip, vref, channelCount, resolution, name)
Definition at line 60 of file advrspi.py.
References webiopi.utils.types.toint().
Referenced by webiopi.devices.analog.advrspi.__init__().
def webiopi.devices.analog.advrspi.__init__ (self, chip = 0, vref = 5.0)
Definition at line 89 of file advrspi.py.
References webiopi.devices.analog.advrspi.__init__().
def webiopi.devices.analog.advrspi.__init__ (self, chip, vref, resolution, name)
Definition at line 171 of file advrspi.py.
References webiopi.devices.analog.advrspi.__init__(), and webiopi.utils.types.toint().
def webiopi.devices.analog.advrspi.__str__ (self)
Definition at line 52 of file advrspi.py.
Variable Documentation
int webiopi.devices.analog.advrspi.CHANNEL_MASK = 0
Definition at line 85 of file advrspi.py.
webiopi.devices.analog.advrspi.name
Definition at line 63 of file advrspi.py.
webiopi.devices.analog.advrspi.value
Definition at line 175 of file advrspi.py.
webiopi.devices.analog.advrspi.values
Definition at line 64 of file advrspi.py.