Yet Another WebIOPi+: webiopi.utils.version Namespace Reference
webiopi.utils.version Namespace Reference
Variables
string VERSION = '0.7.1'
string VERSION_STRING = "WebIOPi/%s/Python%d.%d"
PYTHON_MAJOR = sys.version_info.major
int BOARD_REVISION = 0
list _MAPPING = [[], [], [], []]
tuple rc = re.compile("Revision\s*:\s(.*)\n")
tuple info = f.read()
tuple result = rc.search(info)
tuple hex_cpurev = result.group(1)
tuple cpurev = int(hex_cpurev, 16)
list MAPPING = _MAPPING[BOARD_REVISION]
Variable Documentation
list webiopi.utils.version._MAPPING = [[], [], [], []]
Definition at line 9 of file version.py.
int webiopi.utils.version.BOARD_REVISION = 0
Definition at line 7 of file version.py.
tuple webiopi.utils.version.cpurev = int(hex_cpurev, 16)
Definition at line 24 of file version.py.
list webiopi.utils.version.hex_cpurev = result.group(1)
Definition at line 21 of file version.py.
tuple webiopi.utils.version.info = f.read()
Definition at line 18 of file version.py.
Referenced by webiopi.protocols.coap.COAPServer.enableMulticast(), webiopi.devices.bus.loadModules(), webiopi.__main__.main(), webiopi.protocols.http.HTTPServer.run(), webiopi.protocols.coap.COAPServer.run(), and webiopi.devices.bus.unloadModules().
list webiopi.utils.version.MAPPING = _MAPPING[BOARD_REVISION]
Definition at line 35 of file version.py.
webiopi.utils.version.PYTHON_MAJOR = sys.version_info.major
Definition at line 6 of file version.py.
tuple webiopi.utils.version.rc = re.compile("Revision\s*:\s(.*)\n")
Definition at line 17 of file version.py.
tuple webiopi.utils.version.result = rc.search(info)
Definition at line 19 of file version.py.
Referenced by org.apache.commons.codec.binary.BaseNCodec.decode(), and org.apache.commons.codec.binary.Base64.decode().
string webiopi.utils.version.VERSION = '0.7.1'
Definition at line 4 of file version.py.
string webiopi.utils.version.VERSION_STRING = "WebIOPi/%s/Python%d.%d"
Definition at line 5 of file version.py.