Yet Another WebIOPi+: webiopi.devices.spi Namespace Reference
webiopi.devices.spi Namespace Reference
Classes
class SPI
Functions
def _IOC
def _IOR
def _IOW
def SPI_IOC_MESSAGE
Variables
int _IOC_NRBITS = 8
int _IOC_TYPEBITS = 8
int _IOC_SIZEBITS = 14
int _IOC_DIRBITS = 2
int _IOC_NRSHIFT = 0
tuple _IOC_TYPESHIFT = (_IOC_NRSHIFT+_IOC_NRBITS)
tuple _IOC_SIZESHIFT = (_IOC_TYPESHIFT+_IOC_TYPEBITS)
tuple _IOC_DIRSHIFT = (_IOC_SIZESHIFT+_IOC_SIZEBITS)
int _IOC_NONE = 0
int _IOC_WRITE = 1
int _IOC_READ = 2
int SPI_CPHA = 0x01
int SPI_CPOL = 0x02
tuple SPI_MODE_0 = (0|0)
tuple SPI_MODE_1 = (0|SPI_CPHA)
tuple SPI_MODE_2 = (SPI_CPOL|0)
tuple SPI_MODE_3 = (SPI_CPOL|SPI_CPHA)
tuple SPI_IOC_MAGIC = ord('k')
tuple SPI_IOC_RD_MODE = _IOR(SPI_IOC_MAGIC, 1, 1)
tuple SPI_IOC_WR_MODE = _IOW(SPI_IOC_MAGIC, 1, 1)
tuple SPI_IOC_RD_BITS_PER_WORD = _IOR(SPI_IOC_MAGIC, 3, 1)
tuple SPI_IOC_WR_BITS_PER_WORD = _IOW(SPI_IOC_MAGIC, 3, 1)
tuple SPI_IOC_RD_MAX_SPEED_HZ = _IOR(SPI_IOC_MAGIC, 4, 4)
tuple SPI_IOC_WR_MAX_SPEED_HZ = _IOW(SPI_IOC_MAGIC, 4, 4)
Function Documentation
def webiopi.devices.spi._IOC (direction, t, nr, size) private
Definition at line 38 of file spi.py.
Referenced by webiopi.devices.spi._IOR(), and webiopi.devices.spi._IOW().
def webiopi.devices.spi._IOR (t, number, size) private
Definition at line 43 of file spi.py.
References webiopi.devices.spi._IOC().
def webiopi.devices.spi._IOW (t, number, size) private
Definition at line 45 of file spi.py.
References webiopi.devices.spi._IOC().
Referenced by webiopi.devices.spi.SPI_IOC_MESSAGE().
def webiopi.devices.spi.SPI_IOC_MESSAGE (count)
Definition at line 66 of file spi.py.
References webiopi.devices.spi._IOW().
Referenced by webiopi.devices.spi.SPI.xfer().
Variable Documentation
int webiopi.devices.spi._IOC_DIRBITS = 2
Definition at line 27 of file spi.py.
tuple webiopi.devices.spi._IOC_DIRSHIFT = (_IOC_SIZESHIFT+_IOC_SIZEBITS)
Definition at line 32 of file spi.py.
int webiopi.devices.spi._IOC_NONE = 0
Definition at line 34 of file spi.py.
int webiopi.devices.spi._IOC_NRBITS = 8
Definition at line 24 of file spi.py.
int webiopi.devices.spi._IOC_NRSHIFT = 0
Definition at line 29 of file spi.py.
int webiopi.devices.spi._IOC_READ = 2
Definition at line 36 of file spi.py.
int webiopi.devices.spi._IOC_SIZEBITS = 14
Definition at line 26 of file spi.py.
tuple webiopi.devices.spi._IOC_SIZESHIFT = (_IOC_TYPESHIFT+_IOC_TYPEBITS)
Definition at line 31 of file spi.py.
int webiopi.devices.spi._IOC_TYPEBITS = 8
Definition at line 25 of file spi.py.
tuple webiopi.devices.spi._IOC_TYPESHIFT = (_IOC_NRSHIFT+_IOC_NRBITS)
Definition at line 30 of file spi.py.
int webiopi.devices.spi._IOC_WRITE = 1
Definition at line 35 of file spi.py.
int webiopi.devices.spi.SPI_CPHA = 0x01
Definition at line 48 of file spi.py.
int webiopi.devices.spi.SPI_CPOL = 0x02
Definition at line 49 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_MAGIC = ord('k')
Definition at line 64 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_RD_BITS_PER_WORD = _IOR(SPI_IOC_MAGIC, 3, 1)
Definition at line 79 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_RD_MAX_SPEED_HZ = _IOR(SPI_IOC_MAGIC, 4, 4)
Definition at line 83 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_RD_MODE = _IOR(SPI_IOC_MAGIC, 1, 1)
Definition at line 70 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_WR_BITS_PER_WORD = _IOW(SPI_IOC_MAGIC, 3, 1)
Definition at line 80 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_WR_MAX_SPEED_HZ = _IOW(SPI_IOC_MAGIC, 4, 4)
Definition at line 84 of file spi.py.
tuple webiopi.devices.spi.SPI_IOC_WR_MODE = _IOW(SPI_IOC_MAGIC, 1, 1)
Definition at line 71 of file spi.py.
tuple webiopi.devices.spi.SPI_MODE_0 = (0|0)
Definition at line 51 of file spi.py.
tuple webiopi.devices.spi.SPI_MODE_1 = (0|SPI_CPHA)
Definition at line 52 of file spi.py.
tuple webiopi.devices.spi.SPI_MODE_2 = (SPI_CPOL|0)
Definition at line 53 of file spi.py.
tuple webiopi.devices.spi.SPI_MODE_3 = (SPI_CPOL|SPI_CPHA)
Definition at line 54 of file spi.py.