Document: webiopi
Title: Debian webiopi Manual
Author: <insert document author here>
Abstract: This manual describes what webiopi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webiopi/webiopi.sgml.gz

Format: postscript
Files: /usr/share/doc/webiopi/webiopi.ps.gz

Format: text
Files: /usr/share/doc/webiopi/webiopi.text.gz

Format: HTML
Index: /usr/share/doc/webiopi/html/index.html
Files: /usr/share/doc/webiopi/html/*.html
